# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tfgg484-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/vxs9946/ee799/vxs9946_f2015/bm_rng/xilinx/bm_rng/bm_rng.cache/wt [current_project]
set_property parent.project_path /home/vxs9946/ee799/vxs9946_f2015/bm_rng/xilinx/bm_rng/bm_rng.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_verilog -library xil_defaultlib {
  /home/vxs9946/ee799/vxs9946_f2015/bm_rng/src/lzd.v
  /home/vxs9946/ee799/vxs9946_f2015/bm_rng/src/sin_cos_coef.v
  /home/vxs9946/ee799/vxs9946_f2015/bm_rng/src/taus.v
  /home/vxs9946/ee799/vxs9946_f2015/bm_rng/src/sin_cos_unit.v
  /home/vxs9946/ee799/vxs9946_f2015/bm_rng/src/square_root_unit.v
  /home/vxs9946/ee799/vxs9946_f2015/bm_rng/src/log_unit.v
  /home/vxs9946/ee799/vxs9946_f2015/bm_rng/src/bm_rng.v
}
read_xdc /home/vxs9946/ee799/vxs9946_f2015/bm_rng/xilinx/bm_rng/bm_rng.srcs/constrs_1/new/bm_rng.xdc
set_property used_in_implementation false [get_files /home/vxs9946/ee799/vxs9946_f2015/bm_rng/xilinx/bm_rng/bm_rng.srcs/constrs_1/new/bm_rng.xdc]

synth_design -top bm_rng -part xc7a100tfgg484-1 -flatten_hierarchy none -fanout_limit 64 -fsm_extraction one_hot -keep_equivalent_registers -resource_sharing off -no_lc -shreg_min_size 5
write_checkpoint -noxdef bm_rng.dcp
catch { report_utilization -file bm_rng_utilization_synth.rpt -pb bm_rng_utilization_synth.pb }
